run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/brynnjknight/proxer
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - lll
      source: "^//go:generate "
    - text: "is unused"
      linters:
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0